### ISSUE TITLE
subscribe_route not found

### ISSUE THREAD

**Issue by kethan** [shanewholloway/js-u8-mqtt#1]
It throws error while connecting

**Comment by shanewholloway** [comment]
Thanks for the issue @kethan! Glad you're here and playing with u8-mqtt. The client api continues to rapidly evolve, having recently been extracted from `u8-mqtt-packet`. I appreciate you identifying the connection packet ordering issue, and I've resolved the issue and published it to npm as v0.0.13.

Documenting the u8-mqtt client API is on my backlog, but has been lower down on my priority list. Now with you looking at the client will likely raise this to get done sooner.  The [`u8-mqtt-packet` docs](https://github.com/shanewholloway/js-u8-mqtt-packet/blob/master/docs/api.md) are done, and I'm planning to create docs at the same level for `u8-mqtt` before v0.1.0.

Thanks again!
-Shane

**Comment by shanewholloway** [comment]
I've added a first pass at the [u8-mqtt API docs](https://github.com/shanewholloway/js-u8-mqtt/blob/master/docs/api.md)
