### ISSUE TITLE
how to unsubscribe the topic

### ISSUE THREAD

**Issue by WShuoForever** [shanewholloway/js-u8-mqtt#15]
i want to unsubscribe the topic, but can not find the demo or api

**Comment by shanewholloway** [comment]
the [‘.unsubscribe(topic)’][unsub] method will send the correct packet to the mqtt server.

[unsub]: https://github.com/shanewholloway/js-u8-mqtt/blob/master/docs/pkt-sub.md#unsubscribe-packet

**Comment by WShuoForever** [comment]
> the [‘.unsubscribe(topic)’](https://github.com/shanewholloway/js-u8-mqtt/blob/master/docs/pkt-sub.md#unsubscribe-packet) method will send the correct packet to the mqtt server.

thanks
