### ISSUE TITLE
Clarify reconnect behaviour

### ISSUE THREAD

**Issue by mediafreakch** [shanewholloway/js-u8-mqtt#17]
I run into the following problem: After an unintentional disconnect, the connection is restored successfully as soon as the broker is back online. But any messages broadcasted from the broker after are not picked up by the client.

Is this because the client needs to re-subscribe to the topics manually? Is this by design or a bug/missing feature?

Thanks for clarification.

**Comment by shanewholloway** [comment]
I suggest reading into MQTT semantics around QOS-0 (transient) versus QOS-1 (persistent) publishing of messages, and how that works for subscriptions. In MQTT, the subscription concept is the most recent published "value" of path, not a log replay of prior intermediate values. These are somewhat different software design choices than some other pubsub technologies.

**Comment by mediafreakch** [comment]
I meant messages sent after successful reconnection.

Here's a reproduction repo: https://github.com/mediafreakch/vue3-vite-u8-mqtt .  

Follow the steps in the README to install dependencies and run the mqtt broker.  
Now the app is running on `localhost:5173` and connecting to a mqtt broker at `localhost:8080`.

**Steps to reproduce**

1. Go to http://localhost:5173 and verify that you can send and receive sent messages
2. Now stop the docker container that is running the mqtt broker

Verify that the web app is trying to reconnect (browser console)

3. Now restart the docker container
4. Try to send another message

Expected result: Message is successfully sent, published and received by the client

Actual result: Message is sent and published, but client doesn't process it

**Comment by shanewholloway** [comment]
I found and fixed a bug where `client_id` was not sent upon reconnection. Published fix in `v0.5.3`.

While I was able to see subscriptions restored with the MQTT 3.1.1 (v4) packet protocol, I was unable to do so under the version 5 protocol. Version 5 brokers appear to have different semantics, and I have not dug into the spec for persistent session features.

**Comment by mediafreakch** [comment]
From the [MQTT 5 Spec](https://docs.oasis-open.org/mqtt/mqtt/v5.0/os/mqtt-v5.0-os.html#_Toc3901048):

> A Client that only wants to process messages while connected will set the Clean Start to 1 and set the Session Expiry Interval to 0. It will not receive Application Messages published before it connected and **has to subscribe afresh to any topics that it is interested in each time it connects**.

and

> A Client might be connecting to a Server using a network that provides intermittent connectivity. This Client can use a short Session Expiry Interval so that it can reconnect when the network is available again and continue reliable message delivery. If the Client does not reconnect, allowing the Session to expire, then Application Messages will be lost.

So I tried with the following client configuration, but still no luck:

```
await my_mqtt.connect({
    props: {
      session_expiry_interval: 5 * 60 // 5 minutes
    },
    flags: {
      clean_start: false
    }
});
```

As a workaround I now (re-)subscribe on every (re-)connect.

**Comment by mediafreakch** [comment]
I also updated the demo repo so that the broker persists messages and clients to disk. I also enabled extended logging on the broker. 

With this change, the client can now receive messages after the 1st reconnect. However, after the 2nd re-start of the broker, messages are lost. 

After all I am not convinced that this is an issue with `u8-mqtt`, rather than a matter of the right configuration for the mqtt-broker (mosquitto in this case)

**Comment by shanewholloway** [comment]
In my testing, I used socat to be able to disrupt the connection without mucking with the underlying MQTT server. Specific scripts in the package.json.

excited to see what you find!

**Comment by mediafreakch** [comment]
I spent some time on this topic, tried using this library with a different broker (EMQX), with no success in the matter above. I didn't manage to use `socat` for this purpose.

From what I understand, the messages published after re-connecting *should* make it to the client if persistence is enabled on the broker and the `client_id` remains the same as before the re-connect. The latter is now true with `u8-mqtt@0.5.3`. But it still only work for the first broker re-start. 

Giving up on this. As I said, my workaround is to re-subscribe topics on every connect...
