### ISSUE TITLE
Clarify log_conn and on_ callbacks behaviour

### ISSUE THREAD

**Issue by mediafreakch** [shanewholloway/js-u8-mqtt#18]
It seems like `log_conn`, `on_live` and `on_disconnect` callbacks trigger regardless the actual connection state, meaning when corresponding functions are called rather than depending on the result.

Example: 

```js
// broker wss://localhost:8080 is down
mqtt_v5({
   log_conn(event: string) {
      switch (event) {
          case 'on_disconnect':
             console.log('disconnected')
             break
          case 'on_live':
            console.log('connected')
            break
          default:
      }
  },
  on_live() {
     console.log('connected callback')
  }
}).with_websock('wss://localhost:8080').with_autoreconnect()
```

Prints repeatedly:

```
[...] connected
[...] connected callback
core.jsy:143 WebSocket connection to 'ws://localhost:8080/' failed
[...] disconnected
```

Is this the intended behaviour or a bug?

**Comment by shanewholloway** [comment]
The `on_live` event refers to invocation with an async iterable stream to begin/resume MQTT packet exchanges, not the status of the underlying TCP/websock connection itself.

The `on_disconnect` event is sent after async iteration over the stream upon completion or encountering an exception. Exceptions are thrown when the underlying TCP/websock connection did not establish.

A third event, `on_ready`, is emitted after the MQTT connect packet handshake is complete.

Each connection events have corresponding overidable methods, with default implementations in [`code/core.jsy`](https://github.com/shanewholloway/js-u8-mqtt/blob/master/code/core.jsy)

Upon calling `.with_autoreconnect({delay: 2000})`, the client is designed to repeatedly attempt reconnection every 2000 (default) milliseconds, even if never successfully connected.

---
From your code, unless your localhost MQTT server has a TLS certificate, you likely want to use a non-secure websocket connection string: `'ws://localhost:8080'`

**Comment by mediafreakch** [comment]
I did not know about `on_ready`. Sounds like this is what I need. Not sure why I would use `on_live` though?

**Comment by shanewholloway** [comment]
The default implementation of  ‘on_live’ performs the reconnection logic. Overridable for customizing logic on attempts.

See [‘on_live‘ in core.jsy](https://github.com/shanewholloway/js-u8-mqtt/blob/097c28dd32221fa80413b585225344865ae26d09/code/core.jsy#L40)

**Comment by mediafreakch** [comment]
What does "live" refer to then? Shouldn't this rather be named `on_start` or similar? I am a bit lost when it comes to the lifecycle methods of `u8-mqtt` and how they relate, I have to admit...

**Comment by shanewholloway** [comment]
The difference between "live" and "ready" is whether the `connect` packet has been sent with a success result returned.

That said, I agree that the connection handshaking subsystem could use some refactoring love. It was more of a bolt-on than a designed-in feature.
