### ISSUE TITLE
"(intermediate value)().with_tcp is not a function"

### ISSUE THREAD

**Issue by Mephi-Dross** [shanewholloway/js-u8-mqtt#19]
I'm getting the above error when trying to use the module as described in the README. `with_websock()` works without an issue, but sadly using it is not an option for me.

Code looks as follows:

```javascript
import mqtt_client from 'u8-mqtt'

async function mqttConnect() {
    try {
      let client = mqtt_client().with_tcp(getServerString() + ':1883').with_autoreconnect(); //tcp://localhost:1883

      await client.connect();
      client.subscribe_topic(MQTT_TOPIC, mqttOnMessage);
    } catch (err) {
      console.log(err.message);
    }
  }
```
mqttConnect() gets triggered via a button press. 
Package version is 0.5.3.

I apologize if I'm missing anything obvious, but I'm not really seeing it.

**Comment by shanewholloway** [comment]
Try changing your import to [the web bundler example](https://github.com/shanewholloway/js-u8-mqtt/blob/master/docs/use_from_web_bundler.md):

```javascript
import mqtt_client from 'u8-mqtt/esm/web/index.js'
```

I've tried [accommodating different packagers](https://github.com/shanewholloway/js-u8-mqtt/blob/45b2223db0de8617631b6c35a63c1237430717d0/package.json#L20-L39), but they all seem to have different opinions. Fortunately, most of them support explicit pathing, too.

**Comment by Mephi-Dross** [comment]
I'm afraid the issue persists. I also had a look at the file in question, and there's indeed no `with_tcp()` function in it. Nor in any of the other index.js files under `/esm/`. Instead there's about 50 empty lines, as if something that should be there is missing. All I have is `with_stream()` and `with_websock()`.

**Comment by shanewholloway** [comment]
I was thrown off by the mention of a button. The web version does not have direct TCP access, as the platform does not support that to my knowledge. 

Did you use the [NodeJS](https://github.com/shanewholloway/js-u8-mqtt/blob/master/docs/use_from_nodejs.md) or [Deno](https://github.com/shanewholloway/js-u8-mqtt/blob/master/docs/use_from_deno.md) versions? Are you on a different platform? I ask because the TCP functionality depends on platform APIs.

**Comment by Mephi-Dross** [comment]
Ah sorry, I am using NodeJS. And it appears the issue is with my local installation, because I've built a test project from scratch and that one worked fine. I'll do a bit more troubleshooting on my end, but it doesn't seem to be an issue with the module.
