### ISSUE TITLE
Does this library supports JWT auth?

### ISSUE THREAD

**Issue by ridomin** [shanewholloway/js-u8-mqtt#23]
I'd like to use this library to connect from a browser to a MQTT broker authenticating with JWT tokens. OAUTH2-JWT,

Is this supported?

**Comment by shanewholloway** [comment]
No direct capability, as I have not tested that flow specifically.

That said, this library is made for making compliant MQTT packets, so it should have everything available needed for implementing that flow if you have the specification for it.

if you do create that auth flow, please consider sharing it back as a pull request.
