### ISSUE TITLE
please add Browser usage documentation

### ISSUE THREAD

**Issue by ilgrank** [shanewholloway/js-u8-mqtt#4]
Hi
Thanks for your hard work. Not really an issue, but since the project is targeted (among others) at browser usage, could you please add even just some small browser code sample to get us started?
Thanks!

**Comment by shanewholloway** [comment]
Great suggestion! I’ll do that — hopefully this week.In the meantime you can look at the code in the `index.html` demo which links in `demo/web_v4.mjs`

index.html -- https://github.com/shanewholloway/js-u8-mqtt/blob/master/index.html
demo/web_v4.mjs -- https://github.com/shanewholloway/js-u8-mqtt/blob/master/demo/web_v4.mjs

**Comment by shanewholloway** [comment]
Added [Use heading](https://github.com/shanewholloway/js-u8-mqtt#use) to README in v0.3.0.

Also add copyable [web-cdn](https://github.com/shanewholloway/js-u8-mqtt/blob/master/docs/use_from_web_cdn.md), [web bundler](https://github.com/shanewholloway/js-u8-mqtt/blob/master/docs/use_from_web_bundler.md), [NodeJS](https://github.com/shanewholloway/js-u8-mqtt/blob/master/docs/use_from_nodejs.md), and [deno](https://github.com/shanewholloway/js-u8-mqtt/blob/master/docs/use_from_deno.md) examples.
