### ISSUE TITLE
OT question: Retrieving retained message upon reconnection

### ISSUE THREAD

**Issue by 0ip** [shanewholloway/js-u8-mqtt#6]
My question isn't directly related to the library, but I hope it's okay I'm asking anyway for an opinion.

Upon reconnecting to a broker, I would like to receive the latest/current retained message to get up to speed again. Would simply unsubscribing/(re)subscribing really be the "canonical" approach here?

**Comment by shanewholloway** [comment]
I'm not sure how that's supposed to work. I'd refer you to the specs to get the definitive answer. Also, I believe subscription behavior changed between 3.1.1 (v4) and version 5 of the MQTT specs.

**Comment by 0ip** [comment]
I skimmed the v5 spec but couldn't find any reference to my problem, unfortunately. I'll close the issue here for now.
