### ISSUE TITLE
TLS?

### ISSUE THREAD

**Issue by fatmalama** [shanewholloway/js-u8-mqtt#9]
I looked at the code and I didn't seem to find anything to specify TLS params so I'm assuming it's not supported at all but I'm not sure

**Comment by shanewholloway** [comment]
It wasn't supported, so I created an initial implementation in 5b6c58f730. It needs to be tested on Node and Deno before I publish a new version. Feel free to pull the library down and try it in the meantime.

**Comment by shanewholloway** [comment]
I won't have time to focus of this over the weekend, so I published prerelease `u8-mqtt@0.3.2-0` to allow you to the new TLS support and provide feedback.

**Comment by fatmalama** [comment]
hey @shanewholloway thanks a lot for this, I had other priorities over the week but I'm trying to try it right now -- stumbling a bit on the lack of TS types lol, generated some with dts-gen and going to adapt them properly, but I'm unsure as to what to do with client_id (coming from aws-crt's mqtt client)

their comments on client_id say: "ID to place in CONNECT packet. Must be unique across all devices/clients. If an ID is already in use, the other client will be disconnected."

**Comment by shanewholloway** [comment]
Client ID is a string to uniquely identify your client session on the server for resumption of subscriptions upon reconnect. You can:

- use the library default. See [connect](https://github.com/shanewholloway/js-u8-mqtt/blob/0c901dba6a547432f31f0b0d5c67bd42f8dbcb76/code/base.jsy#L33) 
- provide a string literal 
- provide a list of ‘[“prefix-“, “-suffix”]’ and the library will generate a random identifier for you. See [new_client_id](https://github.com/shanewholloway/js-u8-mqtt/blob/0c901dba6a547432f31f0b0d5c67bd42f8dbcb76/code/base.jsy#L143)


The MQTT spec has more details if you are curious.

**Comment by fatmalama** [comment]
ok the TLS support is actually working properly so I'm closing this :) :+1:
